server:
  port: 8888

spring:
  application:
    name: authentication-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/user

spring.se  security:


jwt:
  secret: mySecret
  expiration: 604800